language: java
addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN
jdk:
  - openjdk8
jobs:
  include:
    - stage: sonar
      script:
      - gralde build
      - sonar-scanner
