
language: java
addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN
jdk:
  - openjdk8
jobs:
  include:
     - stage: unit test
       script:
       - gradle build
     - stage: code scan
       script:
       - gradle sonarqube -PsonarProjectKey=$SONAR_PROJECT_KEY:$TRAVIS_BRANCH -PsonarProjectName=$SONAR_PROJECT_NAME:$TRAVIS_BRANCH -PsonarOrg=$SONAR_ORG
       - chmod 777 checkSonarQualityGateByAPI && ./checkSonarQualityGateByAPI -ProjectKeys=$SONAR_PROJECT_KEY -BranchName=$TRAVIS_BRANCH
