/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.apache.log4j.Logger;

public class Calc {
	final static Logger logger = Logger.getLogger(Calc.class);
    public boolean returnTrue() {
    	logger.info("This method will return true.");
        return true;
    }
}
