/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class CalcTest {
    @Test public void testReturnTrue() {
        Calc classUnderTest = new Calc();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.returnTrue());
    }
}
